//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverymansDetail
    {
        public DeliverymansDetail()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.Salaries = new HashSet<Salary>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string DeliverymanName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public double Salary { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
