//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryProduct
    {
        public InventoryProduct()
        {
            this.InventoryOrdersDetails = new HashSet<InventoryOrdersDetail>();
        }
    
        public int Id { get; set; }
        public string InvProdName { get; set; }
        public int RemQuantity { get; set; }
        public double UnitPrice { get; set; }
    
        public virtual ICollection<InventoryOrdersDetail> InventoryOrdersDetails { get; set; }
    }
}
