//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMSFEntities : DbContext
    {
        public RMSFEntities()
            : base("name=RMSFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cart> Carts { get; set; }
        public DbSet<CustomersDetail> CustomersDetails { get; set; }
        public DbSet<Delivery> Deliveries { get; set; }
        public DbSet<DeliverymansDetail> DeliverymansDetails { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<InventoryOrdersDetail> InventoryOrdersDetails { get; set; }
        public DbSet<InventoryOrdersTotal> InventoryOrdersTotals { get; set; }
        public DbSet<InventoryProduct> InventoryProducts { get; set; }
        public DbSet<ManagersDetail> ManagersDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrdersDetail> OrdersDetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Salary> Salaries { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
