//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CustomersDetails = new HashSet<CustomersDetail>();
            this.DeliverymansDetails = new HashSet<DeliverymansDetail>();
            this.ManagersDetails = new HashSet<ManagersDetail>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<CustomersDetail> CustomersDetails { get; set; }
        public virtual ICollection<DeliverymansDetail> DeliverymansDetails { get; set; }
        public virtual ICollection<ManagersDetail> ManagersDetails { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
